# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/neuraltext',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/neuraltext',
                'lib_path': 'neuraltext'},
  'syms': {'neuraltext.core': {'neuraltext.core.foo': ('core.html#foo', 'neuraltext/core.py')}}}
