name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: notebook test
        uses: fastai/workflows/nbdev-ci@master
      - name: pytest
        run: pytest